export const Constants = {
  ssam: "쌤이랑톡",
  school: "학교랑톡",
  child: "아이랑톡",
  white: "#fff",
  schoolMainColor: "rgb(95, 198, 190)",
  ssamMainColor: "rgb(113, 165, 217)",
  googlePlay: "img/img_btn_logo_google/img_google.png",
  appStore: "img/img_btn_logo_apple/img_apple.png",

  header: {
    ssamMainLogo: "img/img_fulllogo_big/img_fulllogo_big@2x.png",
    schoolMainLogo: "img/img_rangtalk_logo/img_logo@2x.png",
  },
  section: {
    ssamBackMainImg: "img/img_ssamtalk_main/img_main@2x.jpg",
    schoolBackMainImg: "img/img_rangtalk_main/img_main@2x.png",
    ssamPhoneImg: "img/img_mockup_teacher/img_mockup_teacher.jpg",
    schoolPhoneImg: "img/img_mockup_school/img_mockup_school.png",
    ssamIntroTextBgC: "rgba(113, 193, 217, 0.2)",
    schoolIntroTextBgC: "#d8efed",
    ssamIntroTextColor: "#71a5d9",
    schoolIntroTextColor: "#5fc6be",
    ssamIntroNoticeImg: "img/img_sub_04.svg",
    ssamIntroCommuImg: "img/img_sub_05.svg",
    ssamIntroEmerImg: "img/img_sub_06.svg",
    schoolIntroNoticeImg: "img/img_sub_01.svg",
    schoolIntroCommuImg: "img/img_sub_02.svg",
    schoolIntroEmerImg: "img/img_sub_03.svg",
    schoolIntroBgColor: "rgba(134, 185, 180, 0.1)",
    ssamBottomPhone: "img/img_bottom_phone/img_bottom_phone_02@2x.png",
    ssamBottomTalkImg: "img/img_bottom_logo/img_bottom_logo_2@2x.png",
    schoolBottomPhone: "img/img_bottom_phone_school/img_bottom_phone@2x.png",
    schoolBottomTalkImg: "img/img_bottom_logo_school/img_bottom_logo@2x.png",
  },
};
